### ISSUE TITLE
use figure tags for included plantuml

### ISSUE THREAD

**Issue by DavidPyke** [HL7/fhir-registry-protocols-ig#2]
Using \<figure\> and \<figcaption\> with plantuml in IG markdown may be a better way. E.g.,:

    <figure>
    {% include ActorsAndTransactions.svg%}
    <figcaption>Figure 3-1: CREDS Actor Diagram </figcaption>
    </figure>

That makes sure the figure sticks to the diagram

**Comment by keithboone** [comment]
Fixed it
